import type { ModeDefinition } from './types';

export const MODES: ModeDefinition[] = [
  { id: 'patterns', name: 'Pattern Forge', shortName: 'FORGE', description: 'Infer hidden generating rules from changing mathematical states.', loop: 'Observe → Hypothesize → Predict', domains: ['Sequences', 'Induction', 'Number theory'], target: 'Rule induction' },
  { id: 'transform', name: 'Transformation Chamber', shortName: 'VECTOR', description: 'Hold a state in mind while successive operators mutate it.', loop: 'Represent → Transform → Update', domains: ['Linear algebra', 'Geometry', 'Functions'], target: 'Working-memory manipulation' },
  { id: 'constraints', name: 'Constraint Matrix', shortName: 'MATRIX', description: 'Search a solution space while preserving multiple simultaneous constraints.', loop: 'Constrain → Search → Eliminate', domains: ['Combinatorics', 'Graph theory', 'Optimization'], target: 'Constraint reasoning' },
  { id: 'proof', name: 'Proof Forge', shortName: 'PROOF', description: 'Construct and audit chains of necessary implication.', loop: 'Premise → Deduce → Verify', domains: ['Logic', 'Proof', 'Set reasoning'], target: 'Deductive depth' },
  { id: 'orbit', name: 'Orbit Engine', shortName: 'ORBIT', description: 'Reason through cyclic systems using modular arithmetic and coprimality.', loop: 'Map cycle → Find invariant → Predict', domains: ['Modular arithmetic', 'Number theory', 'Cyclic groups'], target: 'Cyclic reasoning' },
  { id: 'bayes', name: 'Bayes Reactor', shortName: 'BAYES', description: 'Update beliefs from base rates, noisy evidence, and conditional likelihoods.', loop: 'Prior → Evidence → Posterior', domains: ['Probability', 'Statistics', 'Bayesian inference'], target: 'Uncertainty reasoning' },
  { id: 'dynamics', name: 'Dynamics Lab', shortName: 'DYNAMICS', description: 'Simulate discrete dynamical systems and reason about trajectories and stability.', loop: 'State → Evolve → Compare', domains: ['Recurrence', 'Dynamical systems', 'Calculus intuition'], target: 'Causal simulation' },
  { id: 'transfer', name: 'Transfer Arena', shortName: 'TRANSFER', description: 'Recognize identical mathematical structure under different surface representations.', loop: 'Strip context → Abstract → Transfer', domains: ['Modeling', 'Isomorphism', 'Generalization'], target: 'Representation transfer' },
  { id: 'hypothesis', name: 'Hypothesis Lab', shortName: 'HYPOTHESIS', description: 'Choose experiments that maximally discriminate between rival mathematical models.', loop: 'Model → Probe → Eliminate', domains: ['Experimental design', 'Functions', 'Information gain'], target: 'Hypothesis efficiency' },
  { id: 'branch', name: 'Branch & Restore', shortName: 'BRANCH', description: 'Preserve a checkpoint, simulate one branch, restore state, then evaluate another.', loop: 'Checkpoint → Branch → Restore → Compare', domains: ['State spaces', 'Mental simulation', 'Working memory'], target: 'State restoration' },
  { id: 'graph', name: 'Graph Command', shortName: 'GRAPH', description: 'Navigate weighted networks and identify globally optimal routes under competing local costs.', loop: 'Map → Search → Optimize', domains: ['Graph theory', 'Shortest paths', 'Optimization'], target: 'Relational optimization' },
];
